#
# Module manifest for module 'cRavenDB'
#
# Generated by: Stephane Erbrech
#
# Generated on: 2016-06-02
#

@{

RootModule = 'cRavenDB.psm1'

ModuleVersion = '0.3'

GUID = '616876a3-25e8-4010-a386-12fbc7a8cde5'

Author = 'Stephane Erbrech'

CompanyName = ''

Copyright = '(c) 2016 Stephane Erbrech. All rights reserved.'

Description = 'DscResource to install ravendb'

PowerShellVersion = '5.0'

FunctionsToExport = '*'

RequiredAssemblies = @('System.IO.Compression.FileSystem')

DscResourcesToExport = @('cRavenDB')

FileList = @("cRavenDB.psm1")

PrivateData = @{

    PSData = @{
        
            Tags = @('DSC', 'DSCResource', 'RavenDB')

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/serbrech/cRavenDB/blob/master/LICENSE'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/serbrech/cRavenDB'

        
    } 

}


}

